const accountsData = [
    {
      name: "Freda",
      email: "fwinger0@fc2.com",
      phone: "5967857969",
      website: "",
      industry: "",
      status: "true",
      remark: "",
    },
    {
      name: "Aloysius",
      email: "amelianby1@lycos.com",
      phone: "4088111631",
      website: "http://sun.com",
      industry: "Real Estate Investment Trusts",
      status: "false",
      remark: "nulla nisl nunc nisl",
    },
    {
      name: "Sarah Chen",
      email: "schen2@techcorp.com",
      phone: "3459876521",
      website: "http://techcorp.io",
      industry: "Information Technology",
      status: "true",
      remark: "Premium client",
    },
    {
      name: "Marcus Rodriguez",
      email: "mrodriguez@salesforce.com",
      phone: "2345678901",
      website: "http://salesforce.com",
      industry: "Software Solutions",
      status: "true",
      remark: "Enterprise account",
    },
    {
      name: "Emma Watson",
      email: "ewatson@healthcare.org",
      phone: "8765432109",
      website: "http://healthcare.org",
      industry: "Healthcare Services",
      status: "true",
      remark: "New account",
    },
    {
      name: "James Smith",
      email: "jsmith@manufacturing.com",
      phone: "5551234567",
      website: "http://manufacturing.com",
      industry: "Manufacturing",
      status: "false",
      remark: "Pending review",
    },
    {
      name: "Linda Johnson",
      email: "ljohnson@retail.com",
      phone: "9876543210",
      website: "http://retail.com",
      industry: "Retail",
      status: "true",
      remark: "VIP client",
    },
    {
      name: "Robert Kim",
      email: "rkim@consulting.com",
      phone: "4567890123",
      website: "http://consulting.com",
      industry: "Consulting Services",
      status: "true",
      remark: "",
    },
    {
      name: "Patricia Garcia",
      email: "pgarcia@education.edu",
      phone: "7890123456",
      website: "http://education.edu",
      industry: "Education",
      status: "false",
      remark: "Contract pending",
    },
    {
      name: "Michael Brown",
      email: "mbrown@finance.com",
      phone: "3216549870",
      website: "http://finance.com",
      industry: "Financial Services",
      status: "true",
      remark: "High priority",
    },
    {
      name: "Jennifer Lee",
      email: "jlee@logistics.com",
      phone: "6789012345",
      website: "http://logistics.com",
      industry: "Logistics",
      status: "true",
      remark: "",
    },
    {
      name: "David Wilson",
      email: "dwilson@energy.com",
      phone: "9012345678",
      website: "http://energy.com",
      industry: "Energy",
      status: "false",
      remark: "Under review",
    },
    {
      name: "Maria Santos",
      email: "msantos@hospitality.com",
      phone: "4321098765",
      website: "http://hospitality.com",
      industry: "Hospitality",
      status: "true",
      remark: "Seasonal client",
    },
    {
      name: "Thomas Anderson",
      email: "tanderson@tech.com",
      phone: "8901234567",
      website: "http://tech.com",
      industry: "Technology",
      status: "true",
      remark: "Key account",
    },
    {
      name: "Lisa Wang",
      email: "lwang@biotech.com",
      phone: "2109876543",
      website: "http://biotech.com",
      industry: "Biotechnology",
      status: "false",
      remark: "In negotiations",
    },
    {
      name: "Kevin Martin",
      email: "kmartin@media.com",
      phone: "7654321098",
      website: "http://media.com",
      industry: "Media",
      status: "true",
      remark: "",
    },
    {
      name: "Anna Kowalski",
      email: "akowalski@transport.com",
      phone: "6543210987",
      website: "http://transport.com",
      industry: "Transportation",
      status: "true",
      remark: "Long-term contract",
    },
    {
      name: "Carlos Ruiz",
      email: "cruiz@construction.com",
      phone: "5432109876",
      website: "http://construction.com",
      industry: "Construction",
      status: "false",
      remark: "Project delayed",
    },
    {
      name: "Michelle Patel",
      email: "mpatel@pharma.com",
      phone: "4321098765",
      website: "http://pharma.com",
      industry: "Pharmaceuticals",
      status: "true",
      remark: "Research partner",
    },
    {
      name: "Daniel Kim",
      email: "dkim@gaming.com",
      phone: "3210987654",
      website: "http://gaming.com",
      industry: "Gaming",
      status: "true",
      remark: "Innovation leader",
    },
    {
      name: "Rachel Green",
      email: "rgreen@fashion.com",
      phone: "2109876543",
      website: "http://fashion.com",
      industry: "Fashion",
      status: "false",
      remark: "Seasonal account",
    },
    {
      name: "Steven Zhang",
      email: "szhang@electronics.com",
      phone: "1098765432",
      website: "http://electronics.com",
      industry: "Electronics",
      status: "true",
      remark: "Technical partner",
    },
    {
      name: "Amanda Silva",
      email: "asilva@food.com",
      phone: "9876543210",
      website: "http://food.com",
      industry: "Food & Beverage",
      status: "true",
      remark: "Quality supplier",
    },
    {
      name: "John Murphy",
      email: "jmurphy@insurance.com",
      phone: "8765432109",
      website: "http://insurance.com",
      industry: "Insurance",
      status: "false",
      remark: "Policy renewal",
    },
    {
      name: "Sophie Martin",
      email: "smartin@aerospace.com",
      phone: "7654321098",
      website: "http://aerospace.com",
      industry: "Aerospace",
      status: "true",
      remark: "Strategic partner",
    },
    {
      name: "William Chang",
      email: "wchang@telecom.com",
      phone: "6543210987",
      website: "http://telecom.com",
      industry: "Telecommunications",
      status: "true",
      remark: "Network provider",
    },
    {
      name: "Elena Rodriguez",
      email: "erodriguez@legal.com",
      phone: "5432109876",
      website: "http://legal.com",
      industry: "Legal Services",
      status: "false",
      remark: "Contract review",
    },
    {
      name: "George Williams",
      email: "gwilliams@agriculture.com",
      phone: "4321098765",
      website: "http://agriculture.com",
      industry: "Agriculture",
      status: "true",
      remark: "Sustainable practices",
    },
    {
      name: "Olivia Brown",
      email: "obrown@marketing.com",
      phone: "3210987654",
      website: "http://marketing.com",
      industry: "Marketing",
      status: "true",
      remark: "Campaign active",
    },
    {
      name: "Ibrahim Ahmed",
      email: "iahmed@renewable.com",
      phone: "2109876543",
      website: "http://renewable.com",
      industry: "Renewable Energy",
      status: "true",
      remark: "Green initiative",
    }
  ];
  
  export default accountsData;